language: android
jdk: oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-24.0.3
        - android-24
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - 'android-sdk-license-.+'
script:
    - ./gradlew check --stacktrace